# Generated by Django 3.1.7 on 2021-05-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0002_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmail',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
