# Generated by Django 3.1.7 on 2021-05-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0004_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
