# Generated by Django 3.1.7 on 2021-06-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0005_registration_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='phone',
        ),
    ]
