# Generated by Django 3.1.7 on 2021-06-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0006_remove_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
