# Generated by Django 3.1.7 on 2021-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0009_remove_gmail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmail',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gmail',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='make_spam',
            field=models.BooleanField(default=False),
        ),
    ]
