# Generated by Django 3.1.7 on 2021-06-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0010_auto_20210602_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='subject',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
