# Generated by Django 3.1.7 on 2021-06-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail', '0011_auto_20210602_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
